WDI-Oryx/wdi-oryx-homework

- Noura_Alhadlaq/week_01/day_02/index.html
- Noura_Alhadlaq/week_01/day_02/main.js
How difficult did you find this (out of 10)?
0 
Was there anything that you struggled with?
no there wasn't.
1 hour
> Homework 2

- Abdullah_AlQahtani/week_01/day_02/Conditionals_LAB/index.html
- Abdullah_AlQahtani/week_01/day_02/Conditionals_LAB/main.js
- Abdullah_AlQahtani/week_01/day_02/Variables_LAB/index.html
- Abdullah_AlQahtani/week_01/day_02/Variables_LAB/main.js
How difficult did you find this (out of 10)? 2 
Was there anything that you struggled with?; variable lab calculation of radius and circumference
Is there anything that you'd like some further information on?; no , thank you
Roughly how long did it take? less than 1 hour
> Homework for day 2

- Mada_Alwuthaynani/week_01/day_02/index.html
- Mada_Alwuthaynani/week_01/day_02/main.js
How difficult did you find this (out of 10)? 3
Was there anything that you struggled with?the pull step.
Is there anything that you'd like some further information on?No.
Roughly how long did it take? 35 minutes most of it gone on submitting it.
> homework day2

- Jafar_Alhajji/week_01/day_02/js_Homework/index.html
- Jafar_Alhajji/week_01/day_02/js_Homework/main.js
How difficult did you find this (out of 10)? 8 out of 10
Was there anything that you struggled with? nothing until now 
Is there anything that you'd like some further information on? 
Roughly how long did it take? 1 hours with some breaks.
> Homework for Day_2

- Sultan_Alsamaani/week_01/day_02/Conditionals_LAB/index.html
- Sultan_Alsamaani/week_01/day_02/Conditionals_LAB/main.js
- Sultan_Alsamaani/week_01/day_02/Variables_LAB/index.html
- Sultan_Alsamaani/week_01/day_02/Variables_LAB/main.js
> w1d2HomeWork

- Leana_Alqurashi/week_01/day_02/Conditionals_LAB/conditionals.js
- Leana_Alqurashi/week_01/day_02/Conditionals_LAB/conditionals_main.html
- Leana_Alqurashi/week_01/day_02/variables_LAB/variables.js
- Leana_Alqurashi/week_01/day_02/variables_LAB/variables_main.html
-     How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 0
-     Was there anything that you struggled with?; No
-     Is there anything that you'd like some further information on?; No
-     Roughly how long did it take? 01:30:00
> day 2 homework

- Faisal_AlQahtani/week_01/day_02/w1d2_Con/index.html
- Faisal_AlQahtani/week_01/day_02/w1d2_Con/main.js
- Faisal_AlQahtani/week_01/day_02/w1d2_Var/index.html
- Faisal_AlQahtani/week_01/day_02/w1d2_Var/main.js
- Faisal_AlQahtani/week_01/day_03/Homework/index.html
- Faisal_AlQahtani/week_01/day_03/Homework/main.js
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 5/10
Was there anything that you struggled with?; string concatenation
Is there anything that you'd like some further information on?; user input
Roughly how long did it take? 1hr
> Homework for Day 2.

- Saud_Almotairy/week_01/day_02/index.html
- Saud_Almotairy/week_01/day_02/main.js
- Saud_Almotairy/week_01/day_03/index.html
- Saud_Almotairy/week_01/day_03/main.js
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 6/10
Was there anything that you struggled with?; The instructions was not compulsory so I went through it and I think it needs some times but is not that hard. So I tried to figure out how to do it but not implement it. 
Is there anything that you'd like some further information on?; I think it should be more clearer instructions until we get along.
Roughly how long did it take? 1 h
> homework wk1 day2

- Dalal_Saeed/week_01/day_02/Conditionals_LAB/index.html
- Dalal_Saeed/week_01/day_02/Conditionals_LAB/main.js
- Dalal_Saeed/week_01/day_02/Variables_LAB/index.html
- Dalal_Saeed/week_01/day_02/Variables_LAB/main.js
- Dalal_Saeed/week_01/day_03/Functions/index.html
- Dalal_Saeed/week_01/day_03/Functions/main.js
3
The Pluralizer function
Is there anything that you’d like some further information on?;
no
1 and half hour 
Thanks
> Homework Day 02

- Wafa_Alturaifi/week_01/day_02/if-statment/index.html
- Wafa_Alturaifi/week_01/day_02/if-statment/main.js
- Wafa_Alturaifi/week_01/day_03/index.html
- Wafa_Alturaifi/week_01/day_03/main.js
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;4/10 
Was there anything that you struggled with?;the git command 
Is there anything that you'd like some further information on?; js methods
Roughly how long did it take?2 hour
> week1-day2

- Halimah_Alshahrani/week_01/day_02/Homework_02/index.html
- Halimah_Alshahrani/week_01/day_02/Homework_02/main.js
- Halimah_Alshahrani/week_01/day_03/Homework_03/index.html
- Halimah_Alshahrani/week_01/day_03/Homework_03/main.js
- Halimah_Alshahrani/week_01/day_04/Homework_04/index.html
- Halimah_Alshahrani/week_01/day_04/Homework_04/main.js
- How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible. 
7 out of 10
- Was there anything that you struggled with? 
No
- Is there anything that you'd like some further information on?
No
- Roughly how long did it take? 3 hours
> Homework for day_02

- Leana_Alqurashi/week_01/day_03/functions.html
- Leana_Alqurashi/week_01/day_03/functionsMain.js
- Leana_Alqurashi/week_01/day_04/ArrayLoops_main.js
- Leana_Alqurashi/week_01/day_04/ArraysLoops.html
-     How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 0
-     Was there anything that you struggled with? No
-     Is there anything that you'd like some further information on? no
-     Roughly how long did it take? 2 hours
> homework day 3, functions

- Sultan_Alsamaani/week_01/day_03/index.html
- Sultan_Alsamaani/week_01/day_03/main.js
- Sultan_Alsamaani/week_01/day_04/index.html
- Sultan_Alsamaani/week_01/day_04/main.js
How difficult did you find this (out of 10)? 2
Was there anything that you struggled with?; no
Is there anything that you'd like some further information on?; no
Roughly how long did it take? 45m
> home work w1 d3

- Jafar_Alhajji/week_01/day_03/js_function_homework/index.html
- Jafar_Alhajji/week_01/day_03/js_function_homework/main.js
- Jafar_Alhajji/week_01/day_05/js_homework_loops/index.html
- Jafar_Alhajji/week_01/day_05/js_homework_loops/main.js
How difficult did you find this (out of 10)? 7out of 10
Was there anything that you struggled with? nothing until now
Is there anything that you'd like some further information on?
Roughly how long did it take? 1 hours
> Homework for day 3 'Function'

- Alanoud_AlRasheed/week_01/day_04/loops/index.html
- Alanoud_AlRasheed/week_01/day_04/loops/main.js
DAY 4 HW: 
1
No.
No, thank you.
An hour.
> added homework day 4

- Njod_Alnasser/week_01/day_04/index.html
- Njod_Alnasser/week_01/day_04/main.js
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;8/10
Was there anything that you struggled with?; some of tasks requirements is not clear 
Is there anything that you'd like some further information on?;No
Roughly how long did it take? 2 hours
>  homework day 4

- Thekra_Alowais/week_01/day_04/arrayAndLoops.html
- Thekra_Alowais/week_01/day_04/arrayAndLoops.js
- Thekra_Alowais/week_01/day_05/MTA.html
- Thekra_Alowais/week_01/day_05/test.js
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 6/10
Was there anything that you struggled with?; The last part of the bonus question. 
Is there anything that you'd like some further information on?;No
Roughly how long did it take? 3
> Homework day4

- Mohammed_Abdulqader/week_01/day_03/Home2.html
- Mohammed_Abdulqader/week_01/day_03/Home2.js
- Mohammed_Abdulqader/week_01/day_04/classwork_2.html
- Mohammed_Abdulqader/week_01/day_04/classwork_2.js
> my homework 

- Noura_Alhadlaq/week_02/day_03/homework w2 d3/DOM-Manipulation/aboutme.html
- Noura_Alhadlaq/week_02/day_03/homework w2 d3/DOM-Manipulation/main.js
- Noura_Alhadlaq/week_02/day_03/homework w2 d3/random-images/index.html
- Noura_Alhadlaq/week_02/day_03/homework w2 d3/random-images/main.js
0 
No there wasn't.
No there wasn't.
1 hour
>  Homework Week2 Day3

- Razan_almusa/week_02/day_03/About-me/index.html
- Razan_almusa/week_02/day_03/About-me/main.js
- Razan_almusa/week_02/day_03/random-number/index.html
- Razan_almusa/week_02/day_03/random-number/main.js
How difficult did you find this (out of 10)?  2
Was there anything that you struggled with?  Give each li the class of "listitem" , i didn't know how i'll do it   
Is there anything that you'd like some further information on? NO
> week2-dsy3-aboutMe

- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/README.md
- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/index.html
- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/starter1.js
- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/starter2.js
- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/style.css
How difficult did you find this (out of 10)?5
Was there anything that you struggled with?;there was No time to explain the question during the lecture.
Is there anything that you'd like some further information on?;No
Roughly how long did it take?hour and half
> HW Week2 D4

- Sarah_AlFadly/week_02/day_04/jQuery-event-HW/README.md
- Sarah_AlFadly/week_02/day_04/jQuery-event-HW/starter1/index.html
- Sarah_AlFadly/week_02/day_04/jQuery-event-HW/starter1/starter1.js
- Sarah_AlFadly/week_02/day_04/jQuery-event-HW/starter1/style.css
- Sarah_AlFadly/week_02/day_04/jQuery-event-HW/starter2/index.html
- Sarah_AlFadly/week_02/day_04/jQuery-event-HW/starter2/starter2.js
- Sarah_AlFadly/week_02/day_04/jQuery-event-HW/starter2/style.css
> Homework for week_02 day_04

- Jafar_Alhajji/week_02/day_04/jQuery-event-HW/README.md
- Jafar_Alhajji/week_02/day_04/jQuery-event-HW/index.html
- Jafar_Alhajji/week_02/day_04/jQuery-event-HW/starter1.js
- Jafar_Alhajji/week_02/day_04/jQuery-event-HW/starter2.js
- Jafar_Alhajji/week_02/day_04/jQuery-event-HW/style.css
How difficult did you find this (out of 10)? 7
Was there anything that you struggled with?game 2
Is there anything that you'd like some further information on? ^_^
Roughly how long did it take?2 hours
> Homework for week2 day4

- Mansour_BinSuqayan/week_02/day_05/intermediate-jquery/index.html
- Mansour_BinSuqayan/week_02/day_05/intermediate-jquery/main.js
- Mansour_BinSuqayan/week_02/day_05/intermediate-jquery/style.css
> This is HW4

- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/index.html
- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/starter1.js
- Mada_Alwuthaynani/week_02/day_04/jQuery-event-HW/starter2.js
- Mada_Alwuthaynani/week_04/day_01/calculater.rb
How difficult did you find this (out of 10)? 3
Was there anything that you struggled with?;no
Is there anything that you'd like some further information on?;no
Roughly how long did it take? an hour
> hw week4 day1

- Alanoud_AlRasheed/week_02/day_04/jQuery-event-HW/index.html
- Alanoud_AlRasheed/week_04/day_01/bmi.rb
- Alanoud_AlRasheed/week_04/day_01/calculator.rb
> HW_W04_D01

- Ali_Alsubaie/week_04/day_01/homework-files/calculator.rb
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 2
Was there anything that you struggled with?; Formulas
Is there anything that you'd like some further information on?; No
Roughly how long did it take? 30 mins without the bonus (1:30 in total)
> W04-D01 Homework

- Noura_Alsubaie/week_04/day_01/calculator.rb
How difficult did you find this (out of 10)? 2 
Was there anything that you struggled with? Mortgage Calculator
Is there anything that you'd like some further information on? No
Roughly how long did it take? an hour
> home task w04 d1

- Faisal_AlQahtani/week_04/day_01/Homework.rb
- Faisal_AlQahtani/week_04/day_01/calculator_HW.md
- Faisal_AlQahtani/week_04/day_01/conditional_LAB.md
- Faisal_AlQahtani/week_04/day_01/guess_LAB.md
- 2
- The Square-root, but then I noticed there was an actual function for it.
- For now, No, I'm getting the hang of understanding and getting used to Ruby.
- About 30mins
> Homework Done Week 4 Day 1

- Razan_Almusa/week_04/day_01/calculator.rb
> week4_day1 HW

- Faisal_AlQahtani/week_04/day_02/README.md
- Faisal_AlQahtani/week_04/day_02/homework.rb
-7
- using loops and if inside a function
-^^ how to find an easier way.
- 1hr
I had some help from Sami and Mansoor, but we all worked together.
> Done Homework Week 4 Day 2

- Alanoud_AlRasheed/week_04/day_02/MTA.rb
> HW_W04_D02

- Noura_Alhadlaq/week_04/day_02/MTA/mta.rb
> week_04 day_02 Homework

- Sarah_AlFadly/week_04/day_02/subway.rb
3/10
Yes, it was how to display an error message if the user entered wrong line or stop
No
3 hours
> Homework for week_04 day_02

- Razan_Almusa/week_04/day_02/subway.rb
6
Was there anything that you struggled with?; 
error 
Roughly how long did it take? 3 hours
> week4_day2 HW

- Leana_Alqurashi/week_04/day_02/MTA.rb
- How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 8
- Was there anything that you struggled with?; I wanted to solve it in the simplest, shortest way possible but I failed 
- Is there anything that you'd like some further information on?; No
- Roughly how long did it take? 3 hours
> Week 4 Day 2 HW - MTA

- Atheer_Minwar/week_04/day_02/MTA.rb
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 5
Was there anything that you struggled with?;  I'm errors prone ....
Is there anything that you'd like some further information on?; No
Roughly how long did it take? 2.5 hours
> MTA lab - incomplete

- Mohammed_Abdulqader/week_04/day_02/HWw4d2/README.md
- Mohammed_Abdulqader/week_04/day_02/HWw4d2/arrays_and_hashes_lab.md
- Mohammed_Abdulqader/week_04/day_02/HWw4d2/supway.rb
hello moath this is my homework for subway
> hello HWD2W4

- Faisal_AlQahtani/week_04/day_03/bank-hw.md
- Faisal_AlQahtani/week_04/day_03/main.rb
- 4
-How to update the name, not sure how I could call the old name so it would then be updated by the user.
- A bit on how to join classes or how to use methods from two classes into one.
-2 hours.
p.s. I had help from many colleagues Ali, Sami, Mansoor, and also you.
> Done Homework Week 4 Day 3

- Noura_Alhadlaq/week_04/day_03/Banks/Bank.rb
5
Was there anything that you struggled with?
nothing 
no there is not 
3 hours
> week_04 day_03 Homework ruby Classes

- Abdullah_AlQahtani/week_04/day_03/classes/main.rb
How difficult did you find this (out of 10)? 2
Was there anything that you struggled with?; nothing
Is there anything that you'd like some further information on?;no 
Roughly how long did it take? 1 hour
> Homework for week 4 day 3

- Razan_Almusa/week_04/day_03/bank.rb
1
Was there anything that you struggled with?; 
1.how to push the user input into array , creating_account function
2. how to run the sql file 
1 hour
> week4_day3 hw

- Leana_Alqurashi/week_04/day_03/bank.rb
- How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 2
- Was there anything that you struggled with?; No
- Is there anything that you'd like some further information on?; No
- Roughly how long did it take? 2 Hs
> Week 4 Day 3 HW - Bank

- Leana_Alqurashi/week_07/day_05/index.html
- Leana_Alqurashi/week_07/day_05/main.js
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 0
Was there anything that you struggled with?; No
Is there anything that you'd like some further information on?; No
Roughly how long did it take? 30 mins
> Week 7 Day 5 HW - ISS Location

- Sarah_AlFadly/week_07/day_05/index.html
- Sarah_AlFadly/week_07/day_05/main.js
> homework for week_07 day_05

- Noura_Alhadlaq/week_07/day_05/API, AJAX Homework /index.html
- Noura_Alhadlaq/week_07/day_05/API, AJAX Homework /main.js
5/10
how to update the contents of the page without reloading. 
APIs. 
4 hours
> Homework week-07 day-05

- Atheer_Minwar/week_07/day_05/ghib/index.html
- Atheer_Minwar/week_07/day_05/ghib/main.js
- Atheer_Minwar/week_07/day_05/ghib/style.css
6/10
Couple of api's  I've tried gave the blocked by CORS error. The response.json part as well . 
CORS , XMLhttp requests 
1 hour for the actual thing (many hours of reading and going through tutorials)
I followed along this tutorial : 
https://www.taniarascia.com/how-to-connect-to-an-api-with-javascript/
> HW W07 D05

- Alanoud_AlRasheed/week_07/day_05/api/index.html
- Alanoud_AlRasheed/week_07/day_05/api/main.js
2
Hiding api key 
no, thanks
30 mns
> HW_W07_D05

- Haya_AlMousa/week_07/day_05/AJAX/index.html
- Haya_AlMousa/week_07/day_05/AJAX/main.js
**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
7 out of 10
**Was there anything that you struggled with?;**
yes with solving some parts of the homework. 
**Is there anything that you'd like some further information on?;**
I'd like more information on the same lesson. 
**Roughly how long did it take?**
Almost 3 hours. I needed more time to go over the lesson again and try to understand it more.
> homework of week 7 day 5

- Noura_Alhadlaq/week_08/day_01/OMDb-API/css/style.css
- Noura_Alhadlaq/week_08/day_01/OMDb-API/index.html
- Noura_Alhadlaq/week_08/day_01/OMDb-API/js/main.js
> Homework week-08 day-01

- Halimah_Alshahrani/week_08/day_01/Homework_d1w8/css/style.css
- Halimah_Alshahrani/week_08/day_01/Homework_d1w8/index.html
- Halimah_Alshahrani/week_08/day_01/Homework_d1w8/js/main.js
How difficult did you find this (out of 10)? 
2 out of 10.
Was there anything that you struggled with?
No.
Is there anything that you'd like some further information on?
Yes , How to convert Xml to Json.
2 hours (Try to believe this).
> Homework_d1w8

- Leana_Alqurashi/week_08/day_01/movies/index.html
- Leana_Alqurashi/week_08/day_01/movies/main.js
- Leana_Alqurashi/week_08/day_01/movies/style.css
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible: 2
Was there anything that you struggled with? No
Is there anything that you'd like some further information on? No
Roughly how long did it take? 1 H
> Week 8 Day 1 HW - omdbapi API

- Sarah_AlFadly/week_08/day_01/index.html
- Sarah_AlFadly/week_08/day_01/main.js
- Sarah_AlFadly/week_08/day_01/style.css
> homework for week_08 day_01

- Alanoud_AlRasheed/week_09/day_01/ReactWeather/app/javascript/components/Routes.js
- Alanoud_AlRasheed/week_09/day_01/ReactWeather/app/views/pages/home.html.erb
- Alanoud_AlRasheed/week_09/day_01/ReactWeather/package.json
- Alanoud_AlRasheed/week_09/day_01/ReactWeather/public/packs/manifest.json
- Alanoud_AlRasheed/week_09/day_01/ReactWeather/yarn.lock
> HW_W09_D02
